server:
  port: 9296

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: http://github.com/Sushmitha-Sannidhi/spring-app-config
          clone-on-start: true


  #-----------------eureka client connection ---------------------------
#eureka:
#  instance:
#    prefer-ip-address : true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}




