server:
  port:8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Ecomm_DB
    username: ${USERNAME}
    password: ${PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
  application:
    name: PRODUCT-SERVICE     #application name
  config:
    import:
      configserver: http://localhost:9296


#    #-----------------eureka client connection ---------------------------
#eureka:
#  instance:
#    prefer-ip-address : true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#       defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}


#management:
#  tracing:
#     sampling:
#      probability: 1.0